
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Run a build script
      run: nx run-many --target=build --all=true
    - name: Zip Artifacts
      run: |
        mkdir -p artifacts
        for dir in $(find dist -mindepth 1 -maxdepth 1 -type d)
        do
          appName=$(basename $dir)
          zip -r "artifacts/${appName}.zip" "$dir"
        done
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zippedArtifacts
        path: artifacts/
